### ISSUE TITLE
Fix Zink/Dxvk extensions

### ISSUE THREAD

**Issue by Mateus2022** [xMeM/sysvk#1]
I would like you to update sysvk to add zink extensions/features and also add VK_EXT_robustness2

I tested zink of tur-repo+sysvk+vk wsi on two devices

Adreno 650 friend phone:
```
WARNING: Some incorrect rendering might occur because the selected Vulkan device (Adreno (TM) 650) doesn't support base Zink requirements: feats.features.logicOp have_EXT_custom_border_color 
=======================================================
    glmark2 2023.01
=======================================================
    OpenGL Information
    GL_VENDOR:      Collabora Ltd
    GL_RENDERER:    zink (Adreno (TM) 650)
    GL_VERSION:     2.1 Mesa 22.0.5
    Surface Config: buf=32 r=8 g=8 b=8 a=8 depth=24 stencil=0 samples=0
    Surface Size:   800x600 windowed
=======================================================
[build] use-vbo=false:ZINK: warning, this is cpu-based conditional rendering, say bye-bye to fps
```
218 score.

 
Mali G52 MP1 (my phone):
~ $ GALLIUM_DRIVER=zink glmark2                                 WARNING: Some incorrect rendering might occur because the selected Vulkan device (Mali-G52) doesn't support base Zink requirements: feats.features.logicOp feats.features.fillModeNonSolid feats.features.shaderClipDistance                                    ** GLX does not support GLX_EXT_swap_control or GLX_MESA_swap_control!                                                          ** Failed to set swap interval. Results may be bounded above by refresh rate.                                                   =======================================================             glmark2 2023.01                                             =======================================================             OpenGL Information                                              GL_VENDOR:      Collabora Ltd                                   GL_RENDERER:    zink (Mali-G52)                                 GL_VERSION:     2.1 Mesa 22.0.5                                 Surface Config: buf=32 r=8 g=8 b=8 a=8 depth=24 stencil=0 samples=0                                                             Surface Size:   800x600 windowed                            =======================================================
107 score

**Comment by xMeM** [comment]
It cannot be implemented with vulkan layer.

**Comment by Mateus2022** [comment]
@xMeM https://github.com/xMeM/termux-packages/commit/da44e3b29b174c760020d88e0829cf845b2b6011#commitcomment-144633354

**Comment by Mateus2022** [comment]
> It cannot be implemented with vulkan layer.

I think it is possible through sysvk or custom_layer to add zink features and dxvk extension, just like adding the x11 swapchain/xcb xlib extensions

**Comment by Mateus2022** [comment]
@xMeM  Well, I wanted to know if it's possible to have an alternative to layer, as it currently doesn't work for anything other than vkcube. I wanted to know if there is an alternative to layer or if it's possible to work on a better implementation with more support for the zink and dxvk extensions.
