### ISSUE TITLE
Sorry for asking here but help wanted 

### ISSUE THREAD

**Issue by Saikatsaha1996** [xMeM/sysvk#2]
I am using your gallium Freedreno driver.. working fine `glxgears glmark2 eglinfo`  but not working Glxinfo it always reporting error any solution about it?
## Proot Glxinfo failed strace 
[proot-glx.txt](https://github.com/user-attachments/files/16737462/proot-glx.txt)

## native Termux Glxinfo failed strace
[glxinfo.txt](https://github.com/user-attachments/files/16737464/glxinfo.txt)

## Failed screenshot 
![Screenshot_2024-08-24-20-11-42-50_84d3000e3f4017145260f7618db1d683](https://github.com/user-attachments/assets/4311789c-48fe-45cc-a615-1a390ea9127a)

## Performance between Zink & Freedreno 

![Screenshot_2024-08-24-11-25-45-36_84d3000e3f4017145260f7618db1d683](https://github.com/user-attachments/assets/45d65bb1-2a4e-4779-a099-d425d9190c63)
![Screenshot_2024-08-24-14-56-30-34_84d3000e3f4017145260f7618db1d683](https://github.com/user-attachments/assets/2eaf25c6-d057-4efd-b16f-a9ff75efa9c3)

**Comment by xMeM** [comment]
https://github.com/xMeM/termux-packages/actions/runs/10121323345
glxinfo seems to work fine in this build of mesa 24.1.3, but is broken in the mesa 24.2.0 build.

**Comment by Saikatsaha1996** [comment]
> https://github.com/xMeM/termux-packages/actions/runs/10121323345 glxinfo seems to work fine in this build of mesa 24.1.3, but is broken in the mesa 24.2.0 build.

Yes now working with `@jeezdisreez` .. https://gitlab.freedesktop.org/Pipetto-crypto/mesa/-/commit/c0fe9bbce70470299f53cee63763ffd57b82d4f2

And @airidosas252 was shared some reviews about gaming.. 

Performance really very much good.. better performance then Zink.. but have some issues like flicking..

Anyway great job too all dev who works for specially aarch64 with Android..
